### PR TITLE
Added nextflow packer scripts

### PR DESCRIPTION
**Pull request by manikandan-thangavelu-rl**
Added nextflow packer scripts

### CODE REVIEW

**Review by RLIndia — CHANGES_REQUESTED** [review]
Do we need to commit the .gitignore file?

**Comment by manikandan-thangavelu-rl** [comment]
We need the .gitignore file for packer related files that needs to ignored

**Review by manikandan-thangavelu-rl — COMMENTED** [review]
We need the .gitignore file for packer related files that needs to ignored

**Review by RLIndia — APPROVED** [review]
Accepting the .gitignore file commits.

**Pull request merged**
